version: '3.8'

services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=nikkeininja
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nikkeininja
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 